version: "3.9"

services:
  application:
    build: .
    image: kefirium-test:latest
    container_name: kefirium_app
    networks:
      - localhost
#    environment:
#      - VIRTUAL_HOST=127.0.0.1
#      - VIRTUAL_PORT=80
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD-SHELL", "php artisan test"]
    volumes:
      - ./application/:/app/
      - ./supervisord/config/supervisord.conf:/etc/supervisord.conf
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/config/kefirium.conf:/etc/nginx/http.d/default.conf:rw
      - ./php-fpm/config/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./php-fpm/config/php.ini:/usr/local/etc/php/php.ini:rw
      - type: bind
        source: ./nginx/logs
        target: /var/log/nginx
      - type: bind
        source: ./php-fpm/logs
        target: /var/log/php-fpm
      - type: bind
        source: ./supervisord/logs
        target: /var/log/supervisord
    depends_on:
      - postgres

  application_postrun:
    depends_on:
      - application
    restart: no
    entrypoint: ["bash", "-c", ]

  postgres:
    image: postgres:15.2
    container_name: kefirium_db
    environment:
      POSTGRES_DB: "kefirium"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - localhost
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d kefirium"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

networks:
  localhost:
    external: true